travis:
  secure:
    BINSTAR_TOKEN: owoo4Yk5ATNjMhPtlrfKo2PpTa46CpKR0MJGLCzeBldvVxjMpegIvrXjwuiv4jXWnnLhXl0ElrPA3RiD7wQlVgKnMLP1OQuj9rSVHWD2H+BqgZm9ULSfKNMwKXQFpGItiFgqVqZD/tnspoWOlvk6+KqVCKgEmulTF/7yrWKPKHGKXFExIAwr05PwGXqEt4+h22JUrgM4gjfom8jK4LgTLpn1aaaG7z43FnsUrWPejaXU9DkOG9LzeuUqqXM7hGFr9/C+DJCOhJIicWG34PeGNP36gXMVXZ0QrZkU4QJlZKVJgjzD/fy77Dc/HtaxPunU/+BMvkKvyP3gw5LWtCUe+AO3/I0aeOpA6YnkqidgORcfbryVQ48GJp2zaLVZ2tS1AWx+tt4x25UcrCi6F69kjZl2LLs2uI8n8JUVQDE/P6HlDcKf0TLcwXy04tBKSeJqehIxbreSJ4eCGOb1q7AtpeLJo3Bf153pISg6sSDkRugu/BjEbuEWu6ptyBDYUL+je1/exbTaebdsfPl8EBToVeXV0eMf7w9kKgrKsb6fALHLwH8jUVWDorEomsNm00gLZtP88Lf3Rg9TZoQYCwcGD1yTqLktXGSM7VdATMDfZJrez2xiAHvgcvd24Bafq3lnXfRSb4apu/CzZTQ4ZP/CU1G+j76MS2mA0+Scy+ffqJY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
