travis:
  secure:
    BINSTAR_TOKEN: lzQ4h2Pa6/aU3rLr5dFPZT+TDbpn56YX4DfuWZvtwA017/+r6+iTYOLbtWJ55GnNviSCdZtNEyqPiZVNSKn25HEwwbaZmAEwKM116eWJnoHkd1RT8YWZqbVBiWpH0VD/ZQxwVXAlEcZuGnkyftCf+GMoOpdx8gW3qP6HkqO/zwmJvuYokAFS9bhVA5FZnuc+/tFia22yg5mdt5t1lxQO4bnLviKUJVXjH5XDqLoihZEtcVsd2U7KKuntCBowE2BK5MK9CFzXgYZrieqpCPHSaUYPvheHsAQCLnOwbuXGsta5N0i2TXrpWJdmYz0oWOqXngQ6krIBRloFwX38OJZ67f2MuNsdxLF3s0xhwR2R58NFqkxI7iTTN6uAOe3ChNgAQYEM1RAxH06lYQv2nYDobFVkcIJQZZtTu357gJ0KlRdkgQYQdwn6mLuijo3Pjoq9xx25ppUPxKsn6jxGpuvKqtwBeSC41b0hZSlibQ5K2Pkg8U6hfOXTatzsIJ2o7VVP0C8SZisvHkVu+acsE7GZz+zkseYACVMg62lJ5giDYXXmhPW6uJI15A/8nf9bm/2nFPIfUbJb0UOFcN4pQ8OVXyc4640r5U8TcDHUWYtgU4XgQSvLGWTNiV+R7H/9oDYww2fwKiFer7tmeF4BMH1qRvxWTtG5yxJToBetDKFX3tE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
